language: python
os:
  - linux
python:
  - "2.7"
  - "3.6"  
install:
  - pip install --upgrade .
  - pip install --upgrade -r requirements/requirements-test.txt
script: pytest
branches:
  only:
    - master
    - dev

